const BLOCK_SIZE = 30;
const BORDER_WIDTH = 4;

const BG_COLOR = '#ffffff';
const RED = '#ff3131';
const BLUE = '#0096ff';

const TOOL_ALPHA = 0.5;

const DARKEN = 0.1;
const LIGHTEN = 0.4;

const HUD_SIZE_MULTIPLIER = 2;
const BRONZE_X = window.innerWidth - BLOCK_SIZE * 12;
const GOLD_X = window.innerWidth - BLOCK_SIZE * 8;
const QUARTZ_X = window.innerWidth - BLOCK_SIZE * 4;
const HUD_Y = 0;

const BRONZE_TEXT_X = window.innerWidth - BLOCK_SIZE * 10;
const GOLD_TEXT_X = window.innerWidth - BLOCK_SIZE * 6;
const QUARTZ_TEXT_X = window.innerWidth - BLOCK_SIZE * 2;

const BRONZE_COL = '#cd7f32';
const BRONZE_CENTER_COL = '#e7994c';

const GOLD_COL = '#ffd700';
const GOLD_CENTER_COL = '#fff11a';

const QUARTZ_COL = '#f9c9d7';
const QUARTZ_CENTER_COL = '#ffe2f0';

const bronze = new Path2D();
bronze.moveTo(BRONZE_X + BLOCK_SIZE/6 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * 1/5 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * 1/2 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * 16/30 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE/6 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
bronze.moveTo(BRONZE_X + BLOCK_SIZE * 1/5 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * 5/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * 13/16 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * (5/6 + 1/128) * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * 16/30 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
bronze.moveTo(BRONZE_X + BLOCK_SIZE * 1/2 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
bronze.lineTo(BRONZE_X + BLOCK_SIZE * 13/16 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);

const bronzeOutline = new Path2D();
bronzeOutline.moveTo(BRONZE_X + BLOCK_SIZE/6 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
bronzeOutline.lineTo(BRONZE_X + BLOCK_SIZE * 1/5 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
bronzeOutline.lineTo(BRONZE_X + BLOCK_SIZE * 5/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
bronzeOutline.lineTo(BRONZE_X + BLOCK_SIZE * 13/16 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
bronzeOutline.lineTo(BRONZE_X + BLOCK_SIZE * (5/6 + 1/128) * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
bronzeOutline.lineTo(BRONZE_X + BLOCK_SIZE * 16/30 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);

const gold = new Path2D();
gold.moveTo(GOLD_X + BLOCK_SIZE/6 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * 1/5 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * 1/2 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * 16/30 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE/6 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
gold.moveTo(GOLD_X + BLOCK_SIZE * 1/5 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * 5/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * 13/16 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * (5/6 + 1/128) * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * 16/30 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
gold.moveTo(GOLD_X + BLOCK_SIZE * 1/2 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
gold.lineTo(GOLD_X + BLOCK_SIZE * 13/16 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);

const goldOutline = new Path2D();
goldOutline.moveTo(GOLD_X + BLOCK_SIZE/6 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);
goldOutline.lineTo(GOLD_X + BLOCK_SIZE * 1/5 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
goldOutline.lineTo(GOLD_X + BLOCK_SIZE * 5/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
goldOutline.lineTo(GOLD_X + BLOCK_SIZE * 13/16 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER);
goldOutline.lineTo(GOLD_X + BLOCK_SIZE * (5/6 + 1/128) * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
goldOutline.lineTo(GOLD_X + BLOCK_SIZE * 16/30 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 4/5 * HUD_SIZE_MULTIPLIER);

const quartz = new Path2D();
quartz.moveTo(QUARTZ_X + BLOCK_SIZE * 7/12 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/8 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE * 3/4 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE * 5/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 7/8 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 11/12 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 10/12 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE * 7/12 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/8 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE * 19/32 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 11/12 * HUD_SIZE_MULTIPLIER);
quartz.moveTo(QUARTZ_X + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE * 19/32 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER);
quartz.lineTo(QUARTZ_X + BLOCK_SIZE * 3/4 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER);

const quartzOutline = new Path2D();
quartzOutline.moveTo(QUARTZ_X + BLOCK_SIZE * 7/12 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/8 * HUD_SIZE_MULTIPLIER);
quartzOutline.lineTo(QUARTZ_X + BLOCK_SIZE * 3/4 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER);
quartzOutline.lineTo(QUARTZ_X + BLOCK_SIZE * 5/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 7/8 * HUD_SIZE_MULTIPLIER);
quartzOutline.lineTo(QUARTZ_X + BLOCK_SIZE/2 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 11/12 * HUD_SIZE_MULTIPLIER);
quartzOutline.lineTo(QUARTZ_X + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 10/12 * HUD_SIZE_MULTIPLIER);
quartzOutline.lineTo(QUARTZ_X + BLOCK_SIZE/4 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE * 3/8 * HUD_SIZE_MULTIPLIER);
quartzOutline.lineTo(QUARTZ_X + BLOCK_SIZE * 7/12 * HUD_SIZE_MULTIPLIER, HUD_Y + BLOCK_SIZE/8 * HUD_SIZE_MULTIPLIER);
